AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

Layout/LineLength:
  Max: 120

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 30

Naming/AccessorMethodName:
  Enabled: false

Naming/FileName:
  Exclude:
    - "bin/*"

Naming/PredicateName:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Exclude:
    - "lib/**/version.rb"
    - "examples/*"
    - "spec/**/*"

Style/Encoding:
  Enabled: true

Style/Lambda:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/WordArray:
  Enabled: false
