#! /usr/bin/env ruby

require "clamp"

class FlipFlop < Clamp::Command

  subcommand "flip", "flip it" do
    def execute
      puts "FLIPPED"
    end
  end

  subcommand "flop", "flop it" do
    def execute
      puts "FLOPPED"
    end
  end
  
end

FlipFlop.run
