#! /usr/bin/env ruby

# An example of subcommands

require "clamp"

Clamp do

  subcommand "foo", "Foo!" do

    subcommand "bar", "Baaaa!" do

      def execute
        puts "FUBAR"
      end

    end

  end

end
