#! /usr/bin/env ruby

require "clop"

class Rename < Clop::Command

  usage "[OPTIONS] TRANSFORM FILE ..."

  argument "TRANSFORM", "a Ruby expression"
  argument "FILE", "a file to rename"
  
  option ["-v", "--verbose"], :flag, "be verbose"

  option ["-n", "--times"], "TIMES", "repetitions", &method(:Integer)

  def initialize(name)
    super
    @times = 1
  end
  
  def execute
    @times.times do
      puts "Blah blah blah" if verbose?
    end
  end
  
end

begin 
  Rename.new("rename").run(ARGV)
rescue Clop::UsageError => e
  $stderr.puts "ERROR: #{e.message}"
  $stderr.puts ""
  $stderr.puts e.command.help
end
