#! /usr/bin/env ruby

require "clop"

class Rename < Clop::Command

  usage "[OPTIONS] TRANSFORM FILE ..."

  argument "TRANSFORM", "a Ruby expression"
  argument "FILE", "a file to rename"
  
  option ["-v", "--verbose"], :flag, "be verbose"

  option ["-n", "--times"], "TIMES", "repetitions" do |n|
    n = Integer(n)
    raise ArgumentError, "too big" if n > 9
    n
  end

  help_option
  
  def initialize(name)
    super
    @times = 1
  end
  
  def execute
    @times.times do
      puts "Blah blah blah" if verbose?
    end
  end
  
end

Rename.run
