#! /usr/bin/env ruby

require "clamp"

Clamp do
  subcommand "hello", "Say hello" do
    def execute
      puts "Hello"
    end
  end

  def subcommand_missing(name)
    abort "Install bye plugin first" if name == "bye"
    super
  end

  def execute
    puts "Why we need this?"
  end

end
