#! /usr/bin/env ruby

require 'clamp'

Clamp do
  subcommand 'hello', 'Say hello' do
    def execute
      puts "Hello"
    end
  end

  def subcommand_missing(name)
    if name == 'bye'
      abort "Install bye plugin first"
    end
  end

  def execute
    puts "Why we need this?"
  end

end
