# frozen_string_literal: true

module Clamp
  module Completion

    # Generates bash shell completion scripts.
    #
    class BashGenerator

      def initialize(command_class, executable_name)
        @command_class = command_class
        @executable_name = executable_name
      end

      def generate
        [
          "# Bash completions for #{@executable_name}",
          "# Generated by Clamp",
          "",
          takes_value_function,
          "",
          completion_function,
          "",
          "complete -F _#{function_name} #{@executable_name}"
        ].push("").join("\n")
      end

      private

      def function_name
        @executable_name.gsub(/[^a-zA-Z0-9_]/, "_")
      end

      def completion_function
        fn = function_name
        [
          "_#{fn}() {",
          "    local cur prev",
          "    if type _init_completion &>/dev/null; then",
          "        _init_completion",
          "    else",
          '        cur="${COMP_WORDS[COMP_CWORD]}"',
          '        prev="${COMP_WORDS[COMP_CWORD-1]}"',
          "    fi",
          "",
          "    local subcmd",
          "    subcmd=$(__#{fn}_find_subcmd)",
          "    if __#{fn}_takes_value \"$prev\" \"$subcmd\"; then",
          "        return",
          "    fi",
          "",
          completions_case("$subcmd"),
          "}",
          "",
          find_subcmd_function
        ].join("\n")
      end

      def find_subcmd_function
        fn = function_name
        subcmds = Completion.collect_subcommand_names(@command_class).join("|")
        [
          "__#{fn}_find_subcmd() {",
          "    local i=1 word subcmd",
          '    while [ "$i" -lt "$COMP_CWORD" ]; do',
          '        word="${COMP_WORDS[$i]}"',
          '        case "$word" in',
          "            -*)",
          "                if __#{fn}_takes_value \"$word\" \"$subcmd\"; then",
          "                    ((i++))",
          "                fi",
          "                ;;",
          "            *)",
          '                case "$word" in',
          "                    #{subcmds})",
          '                        if [ -z "$subcmd" ]; then',
          '                            subcmd="$word"',
          "                        else",
          '                            subcmd="${subcmd}::${word}"',
          "                        fi",
          "                        ;;",
          "                esac",
          "                ;;",
          "        esac",
          "        ((i++))",
          "    done",
          '    echo "$subcmd"',
          "}"
        ].join("\n")
      end

      def completions_case(var)
        entries = {}
        Completion.walk_command_tree(@command_class) do |cmd, path, has_children|
          path_str = path.map { |sub| sub.names.first }.join("::")
          words = Completion.visible_options(cmd).flat_map { |o| Completion.expanded_switches(o) }
          cmd.recognised_subcommands.each { |sub| words.concat(sub.names) } if has_children
          entries[path_str] = words.join(" ")
        end
        lines = ["    case \"#{var}\" in"]
        entries.each do |path, words|
          pattern = path.empty? ? '""' : "\"#{path}\""
          lines << "        #{pattern})"
          lines << "            COMPREPLY=($(compgen -W \"#{words}\" -- \"$cur\"))"
          lines << "            ;;"
        end
        lines << "    esac"
        lines.join("\n")
      end

      def takes_value_function
        entries = {}
        Completion.walk_command_tree(@command_class) do |cmd, path, _has_children|
          path_str = path.map { |sub| sub.names.first }.join("::")
          entries[path_str] = Completion.visible_options(cmd).reject(&:flag?)
                                        .flat_map { |o| Completion.expanded_switches(o) }
        end
        lines = [
          "__#{function_name}_takes_value() {",
          '    local option="$1"',
          '    local subcmd="$2"',
          '    case "$subcmd" in'
        ]
        entries.each do |path, switches|
          next if switches.empty?

          pattern = path.empty? ? '""' : "\"#{path}\""
          lines << "        #{pattern})"
          lines << '            case "$option" in'
          lines << "                #{switches.join('|')}) return 0 ;;"
          lines << "            esac"
          lines << "            ;;"
        end
        lines.push("    esac", "    return 1", "}")
        lines.join("\n")
      end

    end

  end
end
