# frozen_string_literal: true

module Clamp
  module Completion

    # Generates fish shell completion scripts.
    class FishGenerator

      def initialize(command_class, executable_name)
        @command_class = command_class
        @executable_name = executable_name
      end

      def generate
        lines = []
        lines << "# Fish completions for #{@executable_name}"
        lines << "# Generated by Clamp"
        lines << ""
        generate_command(lines, @command_class, [], Set.new)
        "#{lines.join("\n")}\n"
      end

      private

      def generate_command(lines, command_class, path, visited)
        has_children = command_class.has_subcommands? && !visited.include?(command_class)
        visited |= [command_class]

        child_names = has_children ? command_class.recognised_subcommands.flat_map(&:names) : []
        condition = condition_for(path, child_names)

        Completion.visible_options(command_class).each do |option|
          lines << option_completion(option, condition)
        end

        generate_subcommands(lines, command_class, path, condition, visited) if has_children
      end

      def generate_subcommands(lines, command_class, path, condition, visited)
        command_class.recognised_subcommands.each do |sub|
          sub.names.each do |name|
            lines << "complete -c #{@executable_name} -f -n '#{condition}' -a #{name} -d '#{escape(sub.description)}'"
          end
        end

        lines << ""

        command_class.recognised_subcommands.each do |sub|
          generate_command(lines, sub.subcommand_class, path + [sub.names], visited)
        end
      end

      def condition_for(path, child_names)
        if path.empty?
          "__fish_use_subcommand"
        else
          parts = path.map { |names| "__fish_seen_subcommand_from #{names.join(' ')}" }
          parts << "not __fish_seen_subcommand_from #{child_names.join(' ')}" if child_names.any?
          parts.join("; and ")
        end
      end

      def option_completion(option, condition)
        parts = ["complete -c #{@executable_name} -f"]
        parts << "-n '#{condition}'"

        Completion.expanded_switches(option).each do |switch|
          parts << if switch.start_with?("--")
                     "-l #{switch.sub(/^--/, '')}"
                   else
                     "-s #{switch.sub(/^-/, '')}"
                   end
        end

        parts << "-r" unless option.flag?
        parts << "-d '#{escape(option.description)}'"

        parts.join(" ")
      end

      def escape(str)
        str.gsub("'", "\\\\'")
      end

    end

  end
end
